apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-extra-ini
data:
  grafana.ini: |-
    [server]
    serve_from_sub_path = true
    
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer
