mariadb:
  architecture: standalone
  auth:
    existingSecret: wings-mariadb-secret
  passwordUpdateJob:
    enabled: true
    previousPasswords:
      existingSecret: wings-mariadb-secret
  primary:
    service:
      type: LoadBalancer
      nodePorts:
        mysql: 30060
    persistence:
      size: 8Gi
