mariadb:
  architecture: standalone
  auth:
    rootPassword: CHANGEME!
  passwordUpdateJob:
    enabled: true
  primary:
    service:
      type: LoadBalancer
      nodePorts:
        mysql: 30060
    persistence:
      size: 8Gi
