longhorn:
  preUpgradeChecker:
    jobEnabled: false
  defaultSettings:
    replicaZoneSoftAntiAffinity: true
  persistence:
    defaultClassReplicaCount: 1
  service:
    ui:
      type: NodePort
      nodePort: 31761
