apiVersion: v2
name: pterodactyl-panel
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: "v1.11.9"
dependencies:
  - name: mysql
    version: "11.1.20"
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: "20.2.1"
    repository: https://charts.bitnami.com/bitnami