apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "pterodactyl-panel.fullname" . }}-secrets
data:
  DB_USERNAME: {{ .Values.mariadb.auth.username | b64enc }}
  DB_PASSWORD: {{ .Values.mariadb.auth.password | b64enc }}
  DB_DATABASE: {{ .Values.mariadb.auth.database | b64enc }}
  MAIL_USERNAME: {{ .Values.panel.mail.username | b64enc }}
  MAIL_PASSWORD: {{ .Values.panel.mail.username | b64enc }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc }}
