gitea:
  redis-cluster:
    enabled: false

  redis:
    enabled: true

  postgresql:
    enabled: true
    primary:
      persistence:
        size: 10Gi
    global:
      postgresql:
        auth:
          password: CHANGEME!

  postgresql-ha:
    enabled: false

  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - "ReadWriteMany"

  gitea:
    admin:
      username: gitea_admin
      password: CHANGEME!
      email: admin@segs.local
    config:
      server:
        ENABLE_PPROF: true
        DOMAIN: gitea.zenyoung.dev
      database:
        DB_TYPE: postgres
      indexer:
        ISSUE_INDEXER_TYPE: bleve
        REPO_INDEXER_ENABLED: true
    metrics:
      enabled: true

  actions:
    enabled: true
    provisioning:
      enabled: true
    statefulset:
      actRunner:
        config: |
          log:
            level: debug
          cache:
            enabled: false
          runner:
            labels:
              - "node-16:docker://node:16-bullseye"
              - "ubuntu-latest:docker://catthehacker/ubuntu:act-22.04"
      dind:
        extraEnvs:
          - name: DOCKER_HOST
            value: unix:///var/run/user/1000/docker.sock

  service:
    http:
      type: LoadBalancer
      port: 32607
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "32607"
    ssh:
      type: LoadBalancer
      port: 32608
