gitea:
  gitea:
    metrics:
      enabled: true
    config:
      server:
       ENABLE_PPROF: true
       DOMAIN: gitea.zenyoung.dev
    admin:
      username: gitea_admin
      password: CHANGEME!
      email: admin@segs.local

  actions:
    statefulset:
      actRunner:
        config: |
          log:
            level: debug
          cache:
            enabled: false
          runner:
            labels:
              - "node-16:docker://node:16-bullseye"
              - "ubuntu-latest:docker://catthehacker/ubuntu:act-22.04"
    enabled: true
    provisioning:
      enabled: true

  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - "ReadWriteMany"

  service:
    http:
      type: LoadBalancer
      port: 32607
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "32607"
    ssh:
      type: LoadBalancer
      port: 32608
