gitea:
  gitea:
    metrics:
      enabled: true
    config:
      server:
       ENABLE_PPROF: true
       DOMAIN: gitea.zenyoung.dev
    admin:
      username: gitea_admin
      password: CHANGEME!
      email: admin@segs.local

  actions:
    init:
      image:
        repository: node
        tag: 23-alpine3.19
    enabled: true
    provisioning:
      enabled: true

  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - "ReadWriteMany"

  service:
    http:
      type: LoadBalancer
      port: 32607
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "32607"
    ssh:
      type: LoadBalancer
      port: 32608
