prometheus:
  global:
    storageClass: longhorn
  alertmanager:
    service:
      type: NodePort
    persistence:
      enabled: true
  server:
    service:
      type: NodePort
      nodePorts:
        http: "31762"
    persistence:
      enabled: true
