prometheus:
  global:
    storageClass: longhorn
  alertmanager:
    persistence:
      enabled: true
    service:
      type: ClusterIP
  server:
    persistence:
      enabled: true
    service:
      type: ClusterIP
