gitea:
  gitea:
    config:
      server:
       ENABLE_PPROF: true
    admin:
      username: admin
      password: CHANGEME!
      email: admin@segs.local
    metrics:
      enabled: true

  persistence:
    enabled: true
    storageClass: longhorn

  service:
    http:
      type: LoadBalancer
      port: 31763
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "31136"
    ssh:
      type: LoadBalancer
      port: 31764
