apiVersion: v2
name: grafana
description: SEGS Helm Chart for Grafana
type: application
version: 1.1.0
appVersion: "1.16.0"
dependencies:
  - name: grafana
    version: "11.3.26"
    repository: "https://charts.bitnami.com/bitnami"
