grafana:
  admin:
    user: jericho
    password: "CHANGEME"

  persistence:
    storageClass: "local-path"
    size: 1Gi

  service:
    type: NodePort
    nodePorts:
      grafana: "31765"

  config:
    useGrafanaIniFile: true
    grafanaIniConfigMap: grafana-extra-ini
