grafana:
  admin:
    user: admin
    password: CHANGEME
  config:
    useGrafanaIniFile: true
    grafanaIniConfigMap: grafana-extra-ini
  service:
    type: LoadBalancer
    ports:
      grafana: 32603
