homepage:
  config:
    bookmarks:
      - Developer:
          - SEGS Helm Charts:
              - abbr: SEGS-GH
                href: 'https://github.com/jerichosy/helm-charts'
                icon: github.png

    services:
      - GitOps:
          - ArgoCD:
              icon: argocd.png
              href: 'https://172.25.85.182:31760'
              description: CI/CD GitOps delivery tool
          - Gitlab:
              icon: gitlab.png
              href: 'http://localhost'
              description: Code repository and CI/CD pipeline

      - Monitoring:
          - Grafana:
              icon: grafana.png
              href: 'https://172.25.85.182/grafana/'
              description: Monitoring dashboard

      - Management:
          - Longhorn:
              icon: longhorn.png
              href: 'http://172.25.85.182:31761'
              description: Distributed block storage system for Kubernetes
          - Harbor:
              icon: harbor.png
              href: 'https://172.25.85.182:31762'
              description: Artifact and image registry

    widgets:
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: cluster
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - search:
          provider: duckduckgo
          target: _blank

    kubernetes:
      mode: cluster

    settings: null

  serviceAccount:
    create: true
    name: homepage

  enableRbac: true

  ingress:
    main:
      enabled: true
      hosts:
        - host: 172.25.85.182.sslip.io
          paths:
            - path: /
              pathType: Prefix
