apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pterodactyl-panel.fullname" . }}
  labels:
    {{- include "pterodactyl-panel.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pterodactyl-panel.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "pterodactyl-panel.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "pterodactyl-panel.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /app/var
              name: panel-claim
          envFrom:
            - secretRef:
                name: {{ include "pterodactyl-panel.fullname" . }}-secrets
            - configMapRef:
                name: {{ include "pterodactyl-panel.fullname" . }}-configmap
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      restartPolicy: Always
      volumes:
        - name: panel-claim
          persistentVolumeClaim:
            claimName: {{ include "pterodactyl-panel.fullname" . }}-data
