apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pterodactyl-panel.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pterodactyl-panel.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "pterodactyl-panel.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /app/var
              name: panel-claim
            - mountPath: /etc/nginx/http.d
              name: panel-claim
            - mountPath: /etc/letsencrypt
              name: panel-claim
            - mountPath: /app/storage/logs
              name: panel-claim
          envFrom:
            - secretRef:
                name: {{ include "pterodactyl-panel.fullname" . }}-secrets
            - configMapRef:
                name: {{ include "pterodactyl-panel.fullname" . }}-configmap
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            httpGet:
              path: /
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 10
      restartPolicy: Always
      volumes:
        - name: panel-claim
          persistentVolumeClaim:
            claimName: {{ include "pterodactyl-panel.fullname" . }}-data
