apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pterodactyl-panel.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /app/var
              name: panel-claim
            - mountPath: /etc/nginx/http.d
              name: panel-claim
            - mountPath: /etc/letsencrypt
              name: panel-claim
            - mountPath: /app/storage/logs
              name: panel-claim
          envFrom:
            - secretRef:
                name: {{ include "pterodactyl-panel.fullname" . }}-secrets
            - configMapRef:
                name: {{ include "pterodactyl-panel.fullname" . }}-configmap
          readinessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 15
            periodSeconds: 10
      restartPolicy: Always
      volumes:
        - name: panel-claim
          persistentVolumeClaim:
            claimName: {{ include "pterodactyl-panel.fullname" . }}-data
