apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pterodactyl-panel.fullname" . }}
data:
  DB_HOST: {{ printf "%s@%s/%s" .Values.mysql.auth.username, .Values.panel.mysql.host, .Values.mysql.auth.database | b64enc }}
  DB_PASSWORD: {{ .Values.panel.db.password | b64enc }}
  DB_PORT: {{ .Values.mysql.primary.service.ports.mysql | b64enc }}
  MAIL_FROM: {{ .Values.panel.mail.from | b64enc }}
  MAIL_HOST: {{ .Values.panel.mail.host | b64enc }}
  MAIL_PASSWORD: {{ .Values.panel.mail.username | b64enc }}
  MAIL_PORT: {{ .Values.panel.mail.port | quote | b64dec }}
  MAIL_USERNAME: {{ .Values.panel.mail.username | b64enc }}
  REDIS_HOST: {{ printf ":%s@%s:%s" .Values.redis.auth.password, .Values.panel.redis.host, .Values.redis.master.service.ports.redis | b64enc }}
