apiVersion: v1
kind: Service
metadata:
  name: {{ include "pterodactyl-panel.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: 443
