apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "searxng.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
