apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "searxng.fullname" . }}-settings-secret
  annotations:
    kubernetes.io/service-account.name: {{ include "searxng.serviceAccountName" .}}
data:
  settings.yml: {{ include (print $.Template.BasePath "/settings.yml") . | b64enc }}
