homepage:
  config:
    bookmarks:
      - Developer:
          - SEGS Helm Charts:
              - abbr: SEGS-Helm
                href: 'https://github.com/jerichosy/helm-charts'
                icon: github.png

    services:
      - Services:
          - GameServer:
            icon: pterodactyl.png
            href: 'https://gameserver.zenyoung.dev'
            description: Game server panel hosted with Pterodactyl

      - CI/CD:
          - ArgoCD:
              icon: argocd.png
              href: 'https://argocd.k8s.zenyoung.dev'
              description: CI/CD GitOps delivery tool
          - Gitea:
              icon: gitea.png
              href: 'http://gitea.zenyoung.dev'
              description: Code repository and CI/CD pipeline

      - Monitoring:
          - Grafana:
              icon: grafana.png
              href: 'https://grafana.zenyong.dev'
              description: Metric visualization and monitoring dashboard
          - Prometheus:
              icon: prometheus.png
              href: 'http://metrics.k8s.zenyoung.dev'
              description: Systems monitoring and alerting toolkit

      - Infrastructure:
          - Longhorn:
              icon: longhorn.png
              href: 'http://longhorn.k8s.zenyoung.dev'
              description: Distributed block storage system for Kubernetes
          - Harbor:
              icon: harbor.png
              href: 'https://registry.k8s.zenyoung.dev'
              description: Artifact and image registry

    widgets:
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: cluster
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - search:
          provider: custom
          url: https://search.zenyoung.dev
          target: _blank
          suggestionUrl: https://search.zenyoung.dev/autocompleter?q=
          showSearchSuggestions: true

    kubernetes:
      mode: cluster

    settings: null

  serviceAccount:
    create: true
    name: homepage

  enableRbac: true

  ingress:
    main:
      enabled: true
      hosts:
        - host: home.zenyoung.dev
          paths:
            - path: /
              pathType: Prefix
