apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-extra-config
type: Opaque
data:
  Discord-Integration.toml: {{ include "dci.config" . | b64enc }}
  simplebackups-common.toml: {{ include "simplebackups.config" . | b64enc }}
  minimotd.main.conf: {{ include "minimotd.config" . | b64enc }}
---

