apiVersion: v2
name: all-the-mods-9
description: A Helm chart for All The Mods Minecraft Server
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: minecraft
    version: "4.17.0"
    repository: https://itzg.github.io/minecraft-server-charts/
