minimotd:
  enabled: true
  motds:
    # Supported placeholders: {onlinePlayers}, {maxPlayers}
    - line1: "<gold>[★]</gold> <red>ATM 9 Modded Communism™</red> <gold>[★]</gold>"
      line2: "<gold>-=-=-=</gold> <yellow>All hail</yellow> <green>KIA</green> <yellow>and</yellow> <red>SEGS</red><yellow>!</yellow> <gold>=-=-=-</gold>"
  # Setting this to true will disable the hover text showing online player usernames
  disableHover: false

simplebackups:
  enabled: true
  # - FULL_BACKUPS - always creates full backups
  # - MODIFIED_SINCE_LAST - only saves the files which changed since last (partial) backup
  # - MODIFIED_SINCE_FULL - saves all files which changed after the last full backup
  backupType: "FULL_BACKUPS"
  #How often should a full backup be created if only modified files should be saved? This creates a full backup when x minutes are over and the next backup needs to be done. Once a year is default. Range: 1 ~ 5259600.
  fullBackupTimer: "525960"
  # The max amount of backup files to keep. Range: 1 ~ 32767.
  backupsToKeep: "10"
  # The time between two backups in minutes Range: 1 ~ 32767.
  timer: "120"
  # The compression level, 0 is no compression (less cpu usage) and takes a lot of space, 9 is best compression (most cpu usage) and takes less space. -1 is default Range: -1 ~ 9.
  compressionLevel: "7"
  # The max size of storage the backup folder. If it takes more storage, old files will be deleted. Needs to be written as <number><space><storage type>. Valid storage types: B, KB, MB, GB, TB.
  maxDiskSize: "10 GB"

dcIntegration:
  bot:
    token:
    channel: "923633988168478720"

  admin:
    roleIds: ["1002055509366558780"]

  status:
    # Type of the bots status
    # Allowed Values: DISABLED,PLAYING,WATCHING,LISTENING,STREAMING,COMPETING,CUSTOM
    type: CUSTOM
    # PLACEHOLDERS:
    # %online% - Online Players
    # %max% - Maximum Player Amount
    name: "%online% players online"
    nameSingular: "%online% player online"
    nameEmpty: "No one is online"
    # URL of the bots stream when using the status type 'STREAMING'
    streamUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

  inGame:
    # Enable the /discord command to show an custom message with invite URL?
    enabled: false
    message: "Join our discord! https://discord.gg/myserver"
    hoverMessage: "Click to open the invite url"
    inviteUrl: "https://discord.gg/myserver"

  log:
    # Channel ID for the command log channel, leave 0 to disable
    channel: "923636466943418409"
    # PLACEHOLDERS:
    # %sender% - The name of the Command Source
    # %cmd% - executed command (e.g. "say Hello World"
    # %cmd-no-args% - Command without arguments (e.g. "say"
    message: "%sender% executed command `%cmd%`"
    ignore:
      - "list"
      - "help"
      - "?"
    # Turn blacklisted commands into whitelisted commands
    whiteList: false

minecraft:
  image:
    repository: itzg/minecraft-server
    tag: java21-graalvm
    pullPolicy: IfNotPresent
    pullSecret: ""

  resources:
    requests:
      cpu: 1000m
      memory: 10Gi

  minecraftServer:
    eula: "TRUE"
    version: "LATEST"
    type: "AUTO_CURSEFORGE"
    difficulty: hard
    whitelist:
    ops:
    icon: "http://2.bp.blogspot.com/-2O5yrS0ewr0/UWWqjfJiMSI/AAAAAAAAAEc/TWtHsZMh5F8/s1600/New_USSR.png"
    maxPlayers: 20
    maxWorldSize: 2147483647
    allowNether: default
    announcePlayerAchievements: default
    enableCommandBlock: default
    forcegameMode: default
    generateStructures: default
    hardcore: default
    maxBuildHeight: 256
    maxTickTime: 60000
    spawnMonsters: default
    spawnNPCs: default
    spawnProtection: 1
    viewDistance: 7
    gameMode: survival
    motd: "If you see this, then that means Kyoya messed up the MOTD config."
    pvp: default
    levelType: DEFAULT
    worldSaveName: world
    removeOldMods: false
    resourcePackEnforce: false
    onlineMode: false
    enforceSecureProfile: default
    memory: 8G
    overrideServerProperties: true
    serviceType: LoadBalancer
    servicePort: 25565

    modrinth:
      projects:
        - 'simple-voice-chat:4jlHn8n5'
        - 'dcintegration:ILJrSvYW'
        - 'minimotd-reforged:UxOEqoI9'

    autoCurseForge:
      apiKey:
        key: "CHANGEME!"
      pageUrl: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5354808"

    rcon:
      password: "CHANGEME!"
      enabled: true
      port: 25575
      serviceType: ClusterIP

    extraPorts:
      - name: simple-vc
        containerPort: 24454
        protocol: UDP
        service:
          enabled: true
          embedded: false
          annotations: {}
          type: LoadBalancer
          loadBalancerIP: ""
          loadBalancerSourceRanges: []
          externalTrafficPolicy: Cluster
          port: 24454
        ingress:
          ingressClassName: nginx
          enabled: false
          annotations:

      - name: prometheus
        containerPort: 19565
        protocol: TCP
        service:
          enabled: true
          embedded: false
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "19565"
          type: ClusterIP
          port: 19565
        ingress:
          ingressClassName: nginx
          enabled: false
          annotations:

  extraEnv:
    CURSEFORGE_FILES: |
      https://www.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/4694230
      https://www.curseforge.com/minecraft/mc-mods/better-chunk-loading-forge-fabric/files/5310074
      https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric/files/4894789
      https://www.curseforge.com/minecraft/mc-mods/fast-async-world-save-forge-fabric/files/5218101
      https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save/files/5138123
      https://www.curseforge.com/minecraft/mc-mods/krypton-reforged/files/4606534
      https://www.curseforge.com/minecraft/mc-mods/leaky/files/5340919
    MODS: |
      https://github.com/ErdbeerbaerLP/DiscordIntegration-Addon-Repository/raw/master/_Releases/DiscordIntegration-VoiceNotifications-1.1.0.jar
      https://github.com/ErdbeerbaerLP/DiscordIntegration-Addon-Repository/raw/master/_Releases/DiscordIntegration-ExecuteCommand-1.1.0.jar
    ALLOW_FLIGHT: true
    USE_AIKAR_FLAGS: true
    ENABLE_ROLLING_LOGS: true
    TZ: Asia/Manila
    LOG_TIMESTAMP: true
    SIMULATION_DISTANCE: 4

  persistence:
    labels: {}
    annotations: {}
    storageClass: "local-path"
    dataDir:
      enabled: true
      Size: 5Gi
      accessModes:
        - ReadWriteOnce

  livenessProbe:
    command:
      - mc-health
    initialDelaySeconds: 180
    periodSeconds: 5
    failureThreshold: 20
    successThreshold: 1
    timeoutSeconds: 30
  readinessProbe:
    command:
      - mc-health
    initialDelaySeconds: 180
    periodSeconds: 5
    failureThreshold: 20
    successThreshold: 1
    timeoutSeconds: 30
  startupProbe:
    command:
      - mc-health
    enabled: false
    failureThreshold: 30
    periodSeconds: 10

  extraVolumes:
    - volumes:
        - name: extra-config
          secret:
            secretName: all-the-mods-9-extra-config

  initContainers:
    - name: init-extra-config
      image: alpine
      command:
        - 'sh'
        - '-c'
        - 'cp -rf /config/* /data/config/'
      volumeMounts:
        - name: extra-config
          mountPath: /config/Discord-Integration.toml
          subPath: Discord-Integration.toml
        - name: extra-config
          mountPath: /config/simplebackups-common.toml
          subPath: simplebackups-common.toml
        - name: extra-config
          mountPath: /config/minimotd/main.conf
          subPath: minimotd.main.conf
        - name: datadir
          mountPath: /data
---
