dcIntegration:
  bot:
    token:
    channel:

  admin:
    roleIds: ["1002055509366558780"]

  status:
    # Type of the bots status
    # Allowed Values: DISABLED,PLAYING,WATCHING,LISTENING,STREAMING,COMPETING,CUSTOM
    type: CUSTOM
    # PLACEHOLDERS:
    # %online% - Online Players
    # %max% - Maximum Player Amount
    name: "%online% players online"
    nameSingular: "%online% player online"
    nameEmpty: "No-one is online"
    # URL of the bots stream when using the status type 'STREAMING'
    streamUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

  inGame:
    # Enable the /discord command to show an custom message with invite URL?
    enabled: false
    message: "Join our discord! https://discord.gg/myserver"
    hoverMessage: "Click to open the invite url"
    inviteUrl: "https://discord.gg/myserver"

  log:
    # Channel ID for the command log channel, leave 0 to disable
    channel: "0"
    # PLACEHOLDERS:
    # %sender% - The name of the Command Source
    # %cmd% - executed command (e.g. "say Hello World"
    # %cmd-no-args% - Command without arguments (e.g. "say"
    message: "%sender% executed command `%cmd%`"
    ignore:
      - "list"
      - "help"
      - "?"
    # Turn blacklisted commands into whitelisted commands
    whiteList: false

minecraft:
  image:
    repository: itzg/minecraft-server
    tag: java21-graalvm
    pullPolicy: IfNotPresent
    pullSecret: ""

  resources:
    requests:
      cpu: 1000m
      memory: 10Gi

  minecraftServer:
    eula: "TRUE"
    version: "LATEST"
    type: "AUTO_CURSEFORGE"
    difficulty: hard
    whitelist:
    ops:
    icon: "http://2.bp.blogspot.com/-2O5yrS0ewr0/UWWqjfJiMSI/AAAAAAAAAEc/TWtHsZMh5F8/s1600/New_USSR.png"
    maxPlayers: 20
    maxWorldSize: 2147483647
    allowNether: default
    announcePlayerAchievements: default
    enableCommandBlock: default
    forcegameMode: default
    generateStructures: default
    hardcore: default
    maxBuildHeight: 256
    maxTickTime: -1
    spawnMonsters: default
    spawnNPCs: default
    spawnProtection: 16
    viewDistance: 10
    gameMode: survival
    motd: \u00A76[★] \u00A74ATM 9 \u00A7lModded Communism\u00A7r\u00A74™ \u00A76[★]\u00A7r\n\u00A76-=-=-= \u00A7eAll hail \u00A7aKIA \u00A7eand \u00A7cSEGS\u00A7e! \u00A76=-=-=-
    pvp: default
    levelType: DEFAULT
    worldSaveName: world
    removeOldMods: false
    resourcePackEnforce: false
    onlineMode: false
    enforceSecureProfile: default
    memory: 8G
    overrideServerProperties: true
    serviceType: LoadBalancer
    servicePort: 25565

    modrinth:
      projects:
        - 'simple-voice-chat:4jlHn8n5'
        - 'dcintegration:ILJrSvYW'

    autoCurseForge:
      apiKey:
        key: "CHANGEME!"
      pageUrl: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5354808"

    rcon:
      password: "CHANGEME!"
      enabled: true
      port: 25575
      serviceType: ClusterIP

    extraPorts:
      - name: simple-vc
        containerPort: 24454
        protocol: UDP
        service:
          enabled: true
          embedded: false
          annotations: {}
          type: LoadBalancer
          loadBalancerIP: ""
          loadBalancerSourceRanges: []
          externalTrafficPolicy: Cluster
          port: 24454
        ingress:
          ingressClassName: nginx
          enabled: false
          annotations:

      - name: prometheus
        containerPort: 19565
        protocol: TCP
        service:
          enabled: true
          embedded: false
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "19565"
          type: ClusterIP
          port: 19565
        ingress:
          ingressClassName: nginx
          enabled: false
          annotations:

  extraEnv:
    CURSEFORGE_FILES: |
      https://www.curseforge.com/minecraft/mc-mods/prometheus-exporter/files/4694230
    ALLOW_FLIGHT: true
    USE_AIKAR_FLAGS: true
    ENABLE_ROLLING_LOGS: true
    TZ: Asia/Manila
    LOG_TIMESTAMP: true
    SIMULATION_DISTANCE: 6

  persistence:
    labels: {}
    annotations: {}
    storageClass: "local-path"
    dataDir:
      enabled: true
      Size: 5Gi
      accessModes:
        - ReadWriteOnce

  livenessProbe:
    command:
      - mc-health
    initialDelaySeconds: 180
    periodSeconds: 5
    failureThreshold: 20
    successThreshold: 1
    timeoutSeconds: 30
  readinessProbe:
    command:
      - mc-health
    initialDelaySeconds: 180
    periodSeconds: 5
    failureThreshold: 20
    successThreshold: 1
    timeoutSeconds: 30
  startupProbe:
    command:
      - mc-health
    enabled: false
    failureThreshold: 30
    periodSeconds: 10

  extraVolumes:
    - volumeMounts:
        - name: dci-config
          mountPath: /data/config/Discord-Integration.toml
          subPath: Discord-Integration.toml
      volumes:
        - name: dci-config
          secret:
            secretName: all-the-mods-9-extra-config
---
