apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ include "argocd-applicationset.fullname" . }}
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: {{ .Values.git.repoURL }}
      revision: {{ .Values.git.target }}
      directories:
      - path: "*"
  template:
    metadata:
      name: '{{ "{{" }}.path.basename}}'
    spec:
      project: default
      source:
        repoURL: {{ .Values.git.repoURL }}
        targetRevision: HEAD
        path: '{{ "{{" }}.path.path}}'
      destination:
        server: {{ .Values.cluster.server }}
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
