apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "argocd-apps-of-apps.fullname" . }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.target }}
    path: {{ .Values.source.path }}
    directory:
      recurse: true
  destination:
    server: {{ .Values.destination.server }}
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: "*"
      kind: "Application"
      namespace: "*"
      jsonPointers:
        - /spec/syncPolicy/automated
        - /metadata/annotations/argocd.argoproj.io~1refresh
        - /operation
  {{- if .Values.extraIgnoreDifferences }}
    {{- range .Values.extraIgnoreDifferences }}
    - group: {{ .group | quote }}
      kind: {{ .kind | quote }}
      namespace: {{ .namespace | quote }}
      jsonPointers:
        {{- range .jsonPointers }}
        - {{ . }}
        {{- end }}
    {{- end }}
  {{- end }}
